### ISSUE TITLE
导出失败

### ISSUE THREAD

**Issue by Jsondx** [XuQK/Better-Figma-Layer-Exporter#1]
浏览器 chrome 
导出失败：导出错误
弹窗：
![image](https://user-images.githubusercontent.com/23163675/232953748-5fb1a726-4693-484e-bea4-3cd5c52caddb.png)
文件夹：
![image](https://user-images.githubusercontent.com/23163675/232953768-41dc5456-fe92-4cc6-8124-bf108d7dfdd4.png)

**Comment by XuQK** [comment]
经测试，并没有此问题，看看你是不是导出时的文件夹选错了

**Comment by Jsondx** [comment]
没有，我自己建了一个文件夹，是不是需要指定到项目目录啊

**Comment by XuQK** [comment]
不需要，只要选择的文件夹下有命名符合规则的 drawable-*dpi 的相关文件夹即可。
你可以测试一下：
1. 打开一个网页，F12打开控制台，在控制台中输入`const mma = await window.showDirectoryPicker()`，在弹出的选框中选择你要输出的文件夹。
2. 在控制台中输入`for await (const item of mma.values()) {console.log(item)}`，观察打印，是否有预期的文件夹名字出现。

**Comment by Jsondx** [comment]
![image](https://user-images.githubusercontent.com/23163675/232985282-9888b1f4-93c1-40d9-af98-c4473e5429cb.png)
 是有的

**Comment by XuQK** [comment]
emm，，，那你这个问题，就有点匪夷所思了。你用的脚本哪个版本的？如果低于 1.1.3，更新一下试试？

**Comment by Jsondx** [comment]
![image](https://user-images.githubusercontent.com/23163675/232986984-0921e4a5-e10f-4909-9d8a-1b28100c3433.png)
wo我用的是这个版本的 或者说我换一个脚本？

**Comment by XuQK** [comment]
我说的是脚本版本，不是插件
<img width="534" alt="image" src="https://user-images.githubusercontent.com/2867860/232987602-d183adba-30b0-4821-a487-c8a22bddf94d.png">

**Comment by Jsondx** [comment]
哈哈哈哈   zhe这个意思啊

![image](https://user-images.githubusercontent.com/23163675/232987735-4aed59fb-cd00-4e5a-b0fd-5a4bad28ee19.png)

**Comment by XuQK** [comment]
你这是不是选的 night？如果是，那就是没有相关文件夹，夜间模式的文件夹应该是`drawable-night-hdpi`这样。
<img width="547" alt="image" src="https://user-images.githubusercontent.com/2867860/232989089-06bada1d-0085-4c2a-b73f-f583efbadcf4.png">

**Comment by Jsondx** [comment]
> 你这不是选择的夜晚吗？如果是，那就是没有相关文件夹，夜间模式的文件夹应是`drawable-night-hdpi`这样的。 <img alt="图像" width="547" src="https://user-images.githubusercontent.com/2867860/232989089-06bada1d-0085-4c2a-b73f-f583efbadcf4.png">

大佬，确认了，我选了夜间模式了   再次感谢了
